### PR TITLE
Fixed your conjuring issues

### PR DESCRIPTION
**Pull request by Bin4ry1337**

### CODE REVIEW

**Comment by Bin4ry1337** [comment]
Did you find a better way of doing this?

**Comment by L0cTus** [comment]
was trying it alot before but when i changed over to use rotabot alot then nothing worked. as for now only works with food and water

Water example:
//conjure water
castspell:5504;5505;5506;6127;10138;10139;10140
!incombat
breakoncombat
cooldown:3500
triggeredby:2
level>3

// drink
use:drink
mana<53
!incombat
channelingtime:19000
breakoncombat
haveitem<3:trigger:2
afterloot

kinda like this. works in grindmode tho. but problems in rotabot that i use

**Comment by Bin4ry1337** [comment]
Well that is still not as good as the way i did though, since my method is more accurate and fail safe. But i hope Lys will fix it so it checks for new item ids. Then the problem will be solved.

**Comment by L0cTus** [comment]
its kinda the same, here it will just conjure if low on mana and low on water, can sometimes fail i know. the one big problem with yours is that the bot needs to check every single one, and if the char lvl up it is critical for the player to learn the new conjure spell. if the bot can check for multiple items, then the conjure part will be really easy.

**Comment by Bin4ry1337** [comment]
Yup, but anyway you should train every 2nd level anyway though.. or you will start dying a lot.

**Comment by L0cTus** [comment]
i know, but some people dont train right away if they farm at the same spot.

**Comment by L0cTus** [comment]
added in

**Pull request closed without merging**
